#+TITLE: Assessment of approximation method for TSP path length on road networks: a simulation study
#+SUBTITLE: Bachelor Thesis
#+AUTHOR: Koen Stevens, S5302137
#+DATE: \today
#+LANGUAGE: en
#+OPTIONS: toc:nil num:t
#+LATEX_CLASS: article
#+LATEX_CLASS_OPTIONS: [a4paper,11pt]
#+LATEX_HEADER: \usepackage[utf8]{inputenc}
#+LATEX_HEADER: \usepackage{mathtools,amsthm,amssymb,amsmath}
#+LATEX_HEADER: \usepackage{booktabs}
#+LATEX_HEADER: \usepackage{dcolumn}
#+LATEX_HEADER: \usepackage{bm}
#+LATEX_HEADER: \usepackage{graphicx}
#+LATEX_HEADER: \usepackage{subfig}
#+LATEX_HEADER: \usepackage{tabularx}
#+LATEX_HEADER: \usepackage{longtable}
#+LATEX_HEADER: \usepackage[longnamesfirst]{natbib}
#+LATEX_HEADER: \usepackage{marvosym}
#+LATEX_HEADER: \usepackage{eurosym}
#+LATEX_HEADER: \usepackage{hyperref}
#+BIBLIOGRAPHY: literature.bib
#+CITE_EXPORT: natbib
#+BIBLIOGRAPHYSTYLE: rug-econometrics
#+OPTIONS: toc:nil num:t
#+PROPERTY: header-args:python :results output
#+BEGIN_EXPORT latex
\begin{abstract}

\end{abstract}
#+END_EXPORT
#+LATEX: \newpage

* Introduction
The Traveling Salesman Problem (TSP) is an important problem in operations research.
It is particularly relevant for last-mile carriers and other logistics companies where efficient
routing directly impacts cost, time and service quality. Since the number of parcels worldwide has
increased between 2013 and 2022 and is expected to keep increasing [cite:statista], the need for
fast, scalable route planning methods becomes ever more pressing.

The TSP is an NP-hard problem, it is computationally intensive to find the exact solution for
large instances. In many real-world scenarios, the exact optimal routes may not be needed, but
instead a rough, reliable estimate of the optimal route length. For instance, consider a postal delivery company.
This firm may need to assign a certain amount of deliveries or a certain area to each postman.
Reliable estimates for the route length can provide valuable information for making such decisions.

Efficient approximation methods provide a solution for such practical applications where exact
solutions are too computationally intensive to conduct or not feasible due to insufficient data.
These methods aim at approximating the expected optimal total travel time or distance, while using
minimal data and computational effort.

There is extensive research on such approximation methods and how they perform in the euclidean
plane.
Consider $n$ uniformly drawn locations from some area in $\mathbb{R}^2$ with area $A$.
cite:beardwood1959shortest prove the relation:
#+NAME: eq:beardwood
#+BEGIN_EXPORT latex
\begin{align}
	L \to \beta \sqrt{nA}, \quad \text{as } n \to \infty
	\label{eq:beardwood}
\end{align}
#+END_EXPORT
as an estimation for the length of the shortest TSP path measured by Euclidean distance through
these random locations, where $\beta$ is some proportionality constant. This formula is a very
elegant result, and it requires very little data. However, its assumptions,
uniform random locations and euclidean space differ from real-world applications, which are defined
by complex geographic features, such as road networks.

This research investigates how well this approximation method performs when we consider real road
networks. Using OpenStreetMap data, we simulate TSP instances in a wide variety of different urban areas
in the Netherlands, then solve these for the actual shortest paths using the Lin–Kernighan heuristic.
Then we estimate the $\beta$ from equation \ref{eq:beardwood} and analyze the performance of this
formula. Additionally, we compare the results for $\beta$ and the performance across the selected
areas.

In section 2 we dive deeper in the context and previous research in this field. Then, in section 3
we show the methodology ...
* Literature Review
** Applications of the Beardwood formula
We are interested in the performance of formula \ref{eq:beardwood} for $10\leq n\leq90$, in
reasonable amounts of locations a delivery person can visit in a workday. Table
\ref{tab:beta-values} lists values for $\beta$ for some values of $n$, where the points were
generated uniformly and the $L_2$ distance metric was used.
#+LATEX: \begin{table}[htbp]
	#+LATEX: \centering
	#+CAPTION: Empirical estimates of $\beta$ as a function of $n$, $20 \leq n \leq 90$ \cite{lei2015dynamic}
	#+LABEL: tab:beta-values
	|  $n$  | $\beta(n)$ |
	|-------+------------|
	|  20   | 0.8584265  |
	|  30   | 0.8269698  |
	|  40   | 0.8129900  |
	|  50   | 0.7994125  |
	|  60   | 0.7908632  |
	|  70   | 0.7817751  |
	|  80   | 0.7775367  |
	|  90   | 0.7773827  |
	|--------------------|
	#+LATEX: \end{table}
cite:merchan2019empirical use circuity factors to measure the relative detour incurred for
traveling in a road network, compared to the euclidean distance. This circuity factor is defined
as, where $p$ and $q$ are locations:
#+NAME: eq:circuity
#+BEGIN_EXPORT latex
\begin{align}
	c = \frac{d_{c}(p,q)}{d_{L_{2}}(p,q)}
	\label{eq:circuity}
\end{align}
#+END_EXPORT
By construction, $c$ is greater or equal to 1, a value closer to 1 indicates a more efficient network. Then, $\beta_c$
is estimated by $\beta_c=c\beta$. This value $c$, is estimated for three different areas in
São Paulo, for which the results are listed in table \ref{tab:beta-merchan}. These values indicate
real travel distances are on average 2.76 times longer in area 1 compared to the $L_2$ metric.
These values were obtained by uniformly generating $n$ locations (for $n$ ranging from 3 to 250),
computing near-optimal tour lengths under the Euclidean metric, and solving for $\beta$, then
scaling by the empirical circuity factor.
#+LATEX: \begin{table}[htbp]
	#+LATEX: \centering
	#+CAPTION: Estimates of the circuity factor $c$ and its corresponding $\beta_c$ \cite{merchan2019empirical}
	#+LABEL: tab:beta-merchan
	|           |Area 1|Area 2|Area 3|
	|-----------+------+------+------|
	|    $c$    | 2.76 | 2.34 | 1.82 |
	| $\beta_c$ | 2.48 | 2.10 | 1.64 |
	|-----------+------+------+------|
	#+LATEX: \end{table}
It is important to note, however, that the assumptions in this study may limit the generality of 
the findings. In particular, the use of uniformly distributed locations does not accurately reflect 
the spatial distribution of delivery points in real urban environments, where locations tend to 
cluster in residential, commercial, or industrial zones. Furthermore, the circuity factor $c$ can 
vary significantly within a single city, depending on local street patterns, infrastructure, and 
topography. These variations suggest that a fixed circuity factor may oversimplify the complexity 
of real-world delivery contexts, especially when applied to smaller subregions or neighborhoods.
** Lin-Kernighan Heuristic
* Methodology
* References
#+print_bibliography:
* Appendix
#+INCLUDE: "../project/beta_values.org"
