#+TITLE: Assessment of approximation method for TSP path length on road networks: a simulation study
#+SUBTITLE: Bachelor Thesis
#+AUTHOR: Koen Stevens, S5302137
#+DATE: \today
#+LANGUAGE: en
#+OPTIONS: toc:nil num:t
#+LATEX_CLASS: article
#+LATEX_CLASS_OPTIONS: [a4paper,11pt]
#+LATEX_HEADER: \usepackage{mathtools,amsthm,amssymb,amsmath}
#+LATEX_HEADER: \usepackage{booktabs}
#+LATEX_HEADER: \usepackage{dcolumn}
#+LATEX_HEADER: \usepackage{bm}
#+LATEX_HEADER: \usepackage{graphicx}
#+LATEX_HEADER: \usepackage{subfig}
#+LATEX_HEADER: \usepackage{tabularx}
#+LATEX_HEADER: \usepackage{longtable}
#+LATEX_HEADER: \usepackage[longnamesfirst]{natbib}
#+LATEX_HEADER: \usepackage{marvosym}
#+LATEX_HEADER: \usepackage{eurosym}
#+LATEX_HEADER: \usepackage{hyperref}
#+BIBLIOGRAPHY: literature.bib
#+CITE_EXPORT: natbib
#+BIBLIOGRAPHYSTYLE: rug-econometrics
#+OPTIONS: toc:nil num:t
#+PROPERTY: header-args:python :results output
#+BEGIN_EXPORT latex
\begin{abstract}

\end{abstract}
#+END_EXPORT
#+LATEX: \newpage

* Introduction
The Traveling Salesman Problem is an important problem in operations research.
It is particularly relevant for last-mile carriers and other logistics companies where efficient
routing directly impacts cost, time and service quality. Since the number of parcels worldwide has
increased between 2013 and 2022 and is expected to keep increasing [cite:statista], the need for
fast, scalable route planning methods becomes ever more pressing.

The TSP is an NP-hard problem, it is computationally intensive to find the exact solution for
large instances. In many real-world scenarios, the exact optimal routes may not be needed, but
instead a rough, reliable estimate of the optimal route length. For instance, consider a postal delivery company.
This firm may need to assign a certain amount of deliveries or a certain area to each postman.
Reliable estimates for the route length can provide valuable information for making such decisions.

Efficient approximation methods provide a solution for such practical applications where exact
solutions are too computationally intensive to conduct or not feasible due to insufficient data.
These methods aim at approximating the expected optimal total travel time or distance, while using
minimal data and computational effort.

There is extensive research on such approximation methods and how they perform in the euclidean
plane.
Consider $n$ uniformly drawn locations inside some area in $\mathbb{R}^2$ with area $A$.
cite:beardwood1959shortest prove the relation:
#+NAME: eq:beardwood
#+BEGIN_EXPORT latex
\begin{align}
	L \to \beta \sqrt{nA}, \quad \text{as } n \to \infty
	\label{eq:beardwood}
\end{align}
#+END_EXPORT
as an estimation for the length of the shortest TSP path measured by Euclidean distance through
these random locations, where $\beta$ is some proportionality constant. This formula is a very
elegant result, and it requires very little data. However, its assumptions,
uniform random locations and euclidean space differ from real-world applications, which are defined
by complex geographic features, such as road networks.

This research investigates how well this approximation method performs when we consider real road
networks. Using OpenStreetMap data, we simulate TSP instances in a wide variety of different urban areas
in the Netherlands, then solve these for the actual shortest paths using the Lin–Kernighan heuristic.
Then we estimate the $\beta$ from equation \ref{eq:beardwood} and analyze the performance of this
formula. Additionally, we compare the results for $\beta$ and the performance across the selected
areas.

In section 2 we dive deeper in the context and previous research in this field. Then, in section 3
we show the methodology ...
* Literature Review
** Applications of the Beardwood formula
** TSPs on road networks
cite:merchan2019empirical use circuity factors to measure the relative detour incurred for
traveling in a road network, compared to the euclidean distance. This circuity factor is defined
as, where $p$ and $q$ are locations:
#+NAME: eq:circuity
#+BEGIN_EXPORT latex
\begin{align}
	c = \frac{d_{c}(p,q)}{d_{L_{2}}(p,q)}
	\label{eq:circuity}
\end{align}
#+END_EXPORT
$c$ is greater or equal to 1, a value closer to 1 indicates a more efficient network. This
circuity factor has been estimated many times for different road networks, with results ranging
between $1.12$ and $5.60$ [cite:merchan2019empirical]. This is an efficient method of implementing
the impact of traveling over a road network into the models for solving the TSPs, since the euclidean
distance can simply be multiplied by a constant. However, this might be an oversimplification of
reality: this circuity factor might differ strongly from area to area or differ by route length.
Additionally, the locations used were generated from uniform distribution across the area. This
might also be unrealistic since population density differs strongly from area to area, especially
in a city where there is highrise, then the distribution of the delivery locations is clearly not
uniform.
** Lin-Kernighan Heuristic
* Methodology
* References
#+print_bibliography:
* Appendix
#+INCLUDE: "../project/beta_values.org"
